### PR TITLE
Update classification

### PR DESCRIPTION
**Pull request by baolingz**
- classfication.csv has been updated
- sql scripts for`acs_daycareheadstart`,`dcp_sfpsd`, `dcas_colp` and `nysed_activeinstitutions` have been updated

### CODE REVIEW

**Comment by SPTKL** [comment]
@baolingz 
https://github.com/NYCPlanning/db-facilities-tmp/blob/d7b2e35737589017972e53f7302a4fab279ab9db/sql/dcp_sfpsd.sql
can you update the subgroups in the dcp_sfpsd script as well thx

**Comment by baolingz** [comment]
@AmandaDoyle May I know which consistency it follows? I notice most `facsubgrp` are in plural form right now.

**Comment by AmandaDoyle** [comment]
@baolingz Ah sorry.  I thought it was a facility type.  You're correct w/ subgroups being plural

**Comment by baolingz** [comment]
@SPTKL dcp_sfpsd is fixed.

**Pull request merged**
